### ISSUE TITLE
Checkout page

### ISSUE THREAD

**Issue by Treadstudio** [markendley/frste#9]
1. weird thing happening with suburb field?

2. Payment terms - that just needs to display only if the user has "on account" selected. Can we add a field in on the user card that allows the payment terms to be entered?

3. I set up shipping zones but it's not calculating at the checkout - it's just always coming up as free?

4. bring the top of the order panel down to sit in line with the Billing details heading (ref proof) .

5. Address details from the user profile/account details aren't pulling in 

![Screenshot 2023-07-08 at 17-05-01 Checkout 4Site Technologies](https://github.com/markendley/frste/assets/90736622/c085fd14-2609-485c-8d0a-aa6857d22c6c)

**Comment by Treadstudio** [comment]
also same issue with how the figures display

**Comment by Treadstudio** [comment]
can we make the want to ship box nicer as well? maybe just a larger orange framed square that fills orange if selected?

**Comment by markendley** [comment]
> Payment terms - that just needs to display only if the user has "on account" selected. Can we add a field in on the user card that allows the payment terms to be entered?

For each user you gotta check on these boxes, or uncheck if you don't want that payment option avaliable to them.

<img width="583" alt="Screenshot 2023-07-16 at 3 16 04 pm" src="https://github.com/markendley/frste/assets/6570606/0b9e5415-8307-4fb7-a6b3-9a5fdc8ef3ec">

**Comment by markendley** [comment]
the rest should all be fixed now

**Comment by Treadstudio** [comment]
got a few problems....shipping isn't calculating which looks to be affecting payment options

![Screenshot 2023-07-17 at 08-05-25 Checkout 4Site Technologies](https://github.com/markendley/frste/assets/90736622/a8ee3515-e61c-4d6f-83a7-9b915f5412db)

**Comment by Treadstudio** [comment]
with payment options on the user - i was hoping to add a free text field for "pay on account" so they can type in different payment terms for users (e.g. 30, 60, 90 days from invoice)"

currently it's a site wide 30 days 

![Screenshot 2023-07-17 at 08-05-57 Edit User Less40 ‹ 4Site Technologies — WordPress](https://github.com/markendley/frste/assets/90736622/91d48d01-3f45-45e8-aec6-0ae2f90fd3de)

**Comment by markendley** [comment]
I've created a field called "Pay On Account", it's just below.

**Comment by Treadstudio** [comment]
great! i'll leave the ticket assigned to you as still have the shipping/payment issue to sort out

**Comment by markendley** [comment]
all ready!

**Comment by Treadstudio** [comment]
shipping zone still doesn't appear to be picking up/calculating with the input of addresses for orders under $300

**Comment by Treadstudio** [comment]
![Screenshot 2023-07-24 20 32 46](https://github.com/markendley/frste/assets/90736622/93f6988c-7b3d-4080-b2a0-89d76a52759b)

**Comment by markendley** [comment]
oh, some of the shipping rules were mixed out

try now

**Comment by Treadstudio** [comment]
looks like it is working now...i'll create a few test accounts to ensure

**Comment by Treadstudio** [comment]
can't get the test CC payment to work...comes up saying cannot process this payment type? unless that's what it is supposed to do in test mode?

**Comment by markendley** [comment]
I'm able to checkout

gotta screenshot?

**Comment by Treadstudio** [comment]
![Screenshot 2023-08-04 at 11-28-23 Checkout 4Site Technologies](https://github.com/markendley/frste/assets/90736622/a03a62be-fc85-47ce-b898-ca409c76bc81)

**Comment by markendley** [comment]
oh the test keys stopped working, I put in mines

does it work for you now?

**Comment by Treadstudio** [comment]
yep! that did the trick....

**Comment by Treadstudio** [comment]
out of interest on the order received page you redirect to after the payment runs...can we alter the heading/design?

![Screenshot 2023-08-04 at 11-34-14 Checkout 4Site Technologies](https://github.com/markendley/frste/assets/90736622/ab923320-f915-4b90-939f-80e0a126e900)

**Comment by markendley** [comment]
Yes, we can do anything we like.

**Comment by Treadstudio** [comment]
ok cool, thanks
